name: Build Extension

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        browser: [chrome, firefox]
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Bun
      uses: oven-sh/setup-bun@v2
      with:
        bun-version: latest
        
    - name: Install dependencies
      run: bun install --frozen-lockfile
      
    - name: Run linting
      run: bun run lint
      
    - name: Build extension for ${{ matrix.browser }}
      run: |
        if [ "${{ matrix.browser }}" = "firefox" ]; then
          bun run build:firefox
        else
          bun run build
        fi
        
    - name: Create ZIP for ${{ matrix.browser }}
      run: |
        if [ "${{ matrix.browser }}" = "firefox" ]; then
          bun run zip:firefox
        else
          bun run zip
        fi
        
    - name: Verify build output
      run: |
        echo "Checking build output for ${{ matrix.browser }}..."
        
        # Determine the correct output directory
        if [ "${{ matrix.browser }}" = "firefox" ]; then
          OUTPUT_DIR=".output/firefox-mv2"
        else
          OUTPUT_DIR=".output/chrome-mv3"
        fi
        
        echo "Build directory: $OUTPUT_DIR"
        ls -la "$OUTPUT_DIR/"
        
        # Verify required files exist
        if [ ! -f "$OUTPUT_DIR/manifest.json" ]; then
          echo "❌ manifest.json not found"
          exit 1
        fi
        
        echo "✅ Build verification successful for ${{ matrix.browser }}"
        
    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: analista-extension-${{ matrix.browser }}
        path: |
          .output/${{ matrix.browser == 'firefox' && 'firefox-mv2' || 'chrome-mv3' }}/
        retention-days: 30
        
    - name: Upload ZIP artifacts
      uses: actions/upload-artifact@v4
      with:
        name: analista-extension-${{ matrix.browser }}-zip
        path: "*.zip"
        retention-days: 30

  test:
    runs-on: ubuntu-latest
    needs: build
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Bun
      uses: oven-sh/setup-bun@v2
      with:
        bun-version: latest
        
    - name: Install dependencies
      run: bun install --frozen-lockfile
      
    - name: Run format check
      run: bun run format
      
    - name: Run biome check
      run: bun run check

  release:
    runs-on: ubuntu-latest
    needs: [build, test]
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Download Chrome artifacts
      uses: actions/download-artifact@v4
      with:
        name: analista-extension-chrome-zip
        path: ./artifacts/chrome/
        
    - name: Download Firefox artifacts
      uses: actions/download-artifact@v4
      with:
        name: analista-extension-firefox-zip
        path: ./artifacts/firefox/
        
    - name: Create Release
      uses: softprops/action-gh-release@v2
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: |
          ./artifacts/chrome/*.zip
          ./artifacts/firefox/*.zip
        draft: false
        prerelease: false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
